author: wangyongtao # 作者
description: wangyongtao's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags
 Categories: /categories
 Archives: /archives
 Project: /project
 About: /about

# highlight
highlight:
  tomorrow

# catalog
catalog: false # 打赏开关

# donate
donate: false #侧边目录开关

# qrcode
qrcode: true #二维码分享开关

# comment
# you can set gitment, uyan or disqus

# comment: gitment #评论

# gitment config
gitment_owner: taoaiyi1108
gitment_repo: taoaiyi1108.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

# disqus config
disqus_shortname: 

about:
  banner: http://img.pconline.com.cn/images/upload/upc/tx/wallpaper/1311/07/c1/28412984_1383811625819.jpg
  avatar: http://p040q6o73.bkt.clouddn.com/me.jpg
  description: "Try everthing，never give up。"
  weibo_username: 6504255900
  #twitter_username: yanm1ng
  github_username: taoaiyi1108
  #zhihu_username: yummy1121
  #douban_username: yanm1ng
  linkedin_username:
  gitee_username: taoaiyi1108
  email_username: qq_173128525@live.com

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
